# Form implementation generated from reading ui file 'c:\_py\auto-print\assets\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        main_window.resize(350, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setMaximumSize(QtCore.QSize(350, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\_py\\auto-print\\assets\\favicon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        main_window.setWindowIcon(icon)
        main_window.setAutoFillBackground(False)
        main_window.setStyleSheet("color: #000000; \n"
"background: #FFF;")
        self.centralwidget = QtWidgets.QWidget(parent=main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.reload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reload.setEnabled(True)
        self.reload.setGeometry(QtCore.QRect(290, 150, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reload.sizePolicy().hasHeightForWidth())
        self.reload.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.reload.setFont(font)
        self.reload.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reload.setAutoFillBackground(False)
        self.reload.setStyleSheet("border: none;\n"
"border-radius: 15px;\n"
"background-color: transparent;")
        self.reload.setText("")
        self.reload.setIcon(icon)
        self.reload.setIconSize(QtCore.QSize(28, 28))
        self.reload.setObjectName("reload")
        self.logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(62, 35, 225, 119))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("c:\\_py\\auto-print\\assets\\poweredby.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setObjectName("logo")
        self.gpb_log = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gpb_log.setGeometry(QtCore.QRect(10, 185, 330, 150))
        self.gpb_log.setStyleSheet("")
        self.gpb_log.setObjectName("gpb_log")
        self.log_box = QtWidgets.QTextEdit(parent=self.gpb_log)
        self.log_box.setGeometry(QtCore.QRect(15, 30, 300, 110))
        self.log_box.setLineWidth(1)
        self.log_box.setReadOnly(True)
        self.log_box.setPlaceholderText("")
        self.log_box.setObjectName("log_box")
        self.logo.raise_()
        self.gpb_log.raise_()
        self.reload.raise_()
        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "IdeYou Print - v1.0"))
        self.gpb_log.setTitle(_translate("main_window", "Logs"))
